package Telas;

import br.SisAgenda.ListagemEquip;
import br.SisAgenda.PainelCadastColab;
import br.SisAgenda.PainelCadastEquipe;
import br.SisAgenda.PainelCadastTarefa;
import java.awt.CardLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JFrame;

public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();

        PainelCadastColab cadColab = new PainelCadastColab();
        PainelCadastEquipe cadEquipe = new PainelCadastEquipe();

        ListagemEquip lisEquip = new ListagemEquip();

        PainelCadastTarefa cadTaref = new PainelCadastTarefa();

        painelPrincipal.add(cadColab, "PainelCadastColab");
        painelPrincipal.add(cadEquipe, "PainelCadastEquipe");

        painelPrincipal.add(lisEquip, "ListagemEquip");

        painelPrincipal.add(cadTaref, "PainelCadastTarefa");

        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "telaPadrao");

        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jJanelaColab = new javax.swing.JMenu();
        jMenuCadCol = new javax.swing.JMenuItem();
        jListarColab = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCadastroEquipe = new javax.swing.JMenuItem();
        jListarEquipe = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jAddTarefa = new javax.swing.JMenuItem();
        ListarTarefas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jAgendaColab = new javax.swing.JMenuItem();
        jAgendaEquipes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/SisAgenda/imgs/hqdefault.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        painelPrincipal.add(jLabel2, "card2");

        jJanelaColab.setText("Colaborador");

        jMenuCadCol.setText("Cadastrar Colaborador");
        jMenuCadCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadColActionPerformed(evt);
            }
        });
        jJanelaColab.add(jMenuCadCol);

        jListarColab.setText("Listar Colaboradores");
        jListarColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarColabActionPerformed(evt);
            }
        });
        jJanelaColab.add(jListarColab);

        jMenuBar1.add(jJanelaColab);

        jMenu2.setText("Equipes");

        jCadastroEquipe.setText("Cadastrar Equipe");
        jCadastroEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroEquipeActionPerformed(evt);
            }
        });
        jMenu2.add(jCadastroEquipe);

        jListarEquipe.setText("Listar Equipe");
        jListarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListarEquipeActionPerformed(evt);
            }
        });
        jMenu2.add(jListarEquipe);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        jAddTarefa.setText("Adicionar Tarefas");
        jAddTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddTarefaActionPerformed(evt);
            }
        });
        jMenu3.add(jAddTarefa);

        ListarTarefas.setText("Listar Tarefas");
        jMenu3.add(ListarTarefas);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Agenda");

        jAgendaColab.setText("Colaboradores");
        jAgendaColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgendaColabActionPerformed(evt);
            }
        });
        jMenu1.add(jAgendaColab);

        jAgendaEquipes.setText("Equipes");
        jMenu1.add(jAgendaEquipes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadColActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "PainelCadastColab");
    }//GEN-LAST:event_jMenuCadColActionPerformed

    private void jAgendaColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgendaColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgendaColabActionPerformed

    private void jAddTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddTarefaActionPerformed
        //CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        //cl.show(painelPrincipal, "PainelCadastTarefa");
    }//GEN-LAST:event_jAddTarefaActionPerformed

    private void jListarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarEquipeActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "ListagemEquip");
    }//GEN-LAST:event_jListarEquipeActionPerformed

    private void jCadastroEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroEquipeActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "PainelCadastEquipe");
    }//GEN-LAST:event_jCadastroEquipeActionPerformed

    private void jListarColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarColabActionPerformed
        
    }//GEN-LAST:event_jListarColabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListarTarefas;
    private javax.swing.JMenuItem jAddTarefa;
    private javax.swing.JMenuItem jAgendaColab;
    private javax.swing.JMenuItem jAgendaEquipes;
    private javax.swing.JMenuItem jCadastroEquipe;
    private javax.swing.JMenu jJanelaColab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jListarColab;
    private javax.swing.JMenuItem jListarEquipe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadCol;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
